version: '3'

services:
  subscription-mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=subscription_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
      - TZ=Europe/Berlin
    ports:
      - 3308:3306
    volumes:
      - /data/mysql
  subscription-service-app:
    image: newsletter-subscription-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - subscription-mysql-docker-container
    ports:
      - 8087:8080
    volumes:
      - /data/newsletter-subscription-service-app