version: '3'

services:
  subscription-service-app:
    image: newsletter-subscription-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8088:8080
    volumes:
      - /data/newsletter-subscription-service-app