version: '3.1'

services:
    mysql-docker-container:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=subscriptiondb
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
      volumes:
      - /Users/cfernandez/dockerVolumes/mysql_container
      ports:
        - 3308:3306
