info:
  name: @project.name@
  description: @project.description@
  apiVersion: "1.0"
  build:
    artifact: @project.artifactId@
    version: @project.version@

spring:
  datasource:
    url: jdbc:h2:mem:subscription_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
        hibernate:
            format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

